config/routes.rb
FairyWhaleDemo::Application.routes.draw do
  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  resources :comments
  resources :categories
  resources :types
  resources :node_comments
  resources :nodes

  root :to => 'pages#home' #root
  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/home', :to => 'pages#home' #get "pages/home"
  match '/stories',   :to => 'nodes#stories' #get "pages/zgodbe"
  match '/about',   :to => 'pages#about' #get "pages/zgodba"
  match '/newstory', :to => 'nodes#new'
  match '/nodes/:id/add', :to => 'nodes#addnode'
  resources :nodes do
    member do
      get :zgodba
    end
  end

end

app/models/node.rb
class Node < ActiveRecord::Base

  belongs_to :user
  belongs_to :category
  belongs_to :type
  
  has_many :relationships, :foreign_key => "rootNode_id",
                           :dependent => :destroy
  has_many :story, :through => :relationships, 
                     :source => :contentNode
  
  def stories?(contentNode)
    relationships.find_by_contentNode_id(contentNode)
  end

  def story!(contentNode)
    relationships.create!(:contentNode_id => contentNode.id)
  end

  def destroyStory!(contentNode)
    relationships.find_by_contentNode_id(contentNode).destroy
  end
end

app/controllers/nodes_controller.rb
class NodesController < ApplicationController
  # GET /nodes
  # GET /nodes.json
  def index
    @nodes = Node.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @nodes }
    end
  end

  # GET /nodes/1
  # GET /nodes/1.json
  def show
    @node = Node.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @node }
    end
  end

  # GET /nodes/new
  # GET /nodes/new.json
  def new
    @node = Node.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @node }
    end
  end

  def addnode
    @node = current_user.nodes.build(params[:node])
    end 

  def stories
    @node = Node.where(:root => true)
        respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @node }
    end
  end

  # GET /nodes/1/edit
  def edit
    @node = Node.find(params[:id])
  end

  # POST /nodes
  # POST /nodes.json
  def create
    @node = current_user.nodes.build(params[:node])
    #@node = Node.new(params[:node])

    respond_to do |format|
      if @node.save
        format.html { redirect_to @node, notice: 'Node was successfully created.' }
        format.json { render json: @node, status: :created, location: @node }
      else
        format.html { render action: "new" }
        format.json { render json: @node.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /nodes/1
  # PUT /nodes/1.json
  def update
    @node = Node.find(params[:id])

    respond_to do |format|
      if @node.update_attributes(params[:node])
        format.html { redirect_to @node, notice: 'Node was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @node.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nodes/1
  # DELETE /nodes/1.json
  def destroy
    @node = Node.find(params[:id])
    @node.destroy

    respond_to do |format|
      format.html { redirect_to nodes_url }
      format.json { head :ok }
    end
  end
end

app/helpers/nodes_helper.rb
module NodesHelper
end

app/views/nodes/_form.html.erb
<%= form_for(@node) do |f| %>
  <% if @node.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@node.errors.count, "error") %> prohibited this node from being saved:</h2>

      <ul>
      <% @node.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :root %><br />
    <%= f.check_box :root %>
  </div>
  <div class="field">
    <%= f.label :category_id %><br />
    <%= f.select(:category_id, Category.all.collect{|p| [p.title, p.id]} )%>
  </div>
  <div class="field">
    <%= f.label :type_id %><br />
    <%= f.select(:type_id, Type.all.collect{|p| [p.title, p.id]} ) %>
  </div>
    <br />
  Testni nameni
  <div class="field">
    <%= f.label :voteUp %><br />
    <%= f.text_field :voteUp %>
  </div>
  <div class="field">
    <%= f.label :voteDown %><br />
    <%= f.text_field :voteDown %>
  </div>
    <div class="field">
    <%= f.label :views %><br />
    <%= f.text_field :views %>
  </div>
    <br />
  <div class="actions">
    <%= f.submit %>
  </div>
  
  


<% end %>

app/views/nodes/addnode.html.erb
<h1>Add content</h1>

<%= form_for(@node) do |f| %>
  <% if @node.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@node.errors.count, "error") %> prohibited this node from being saved:</h2>

      <ul>
      <% @node.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>

  <div class="field">
    <%= f.label :category_id %><br />
    <%= f.select(:category_id, Category.all.collect{|p| [p.title, p.id]} )%>
  </div>
  <div class="field">
    <%= f.label :type_id %><br />
    <%= f.select(:type_id, Type.all.collect{|p| [p.title, p.id]} ) %>
  </div>
    <br />
  Testni nameni
  <div class="field">
    <%= f.label :voteUp %><br />
    <%= f.text_field :voteUp %>
  </div>
  <div class="field">
    <%= f.label :voteDown %><br />
    <%= f.text_field :voteDown %>
  </div>
    <div class="field">
    <%= f.label :views %><br />
    <%= f.text_field :views %>
  </div>
    <br />
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Back', nodes_path %>

app/views/nodes/edit.html.erb
<h1>Editing node</h1>

<%= render 'form' %>

<%= link_to 'Show', @node %> |
<%= link_to 'Back', nodes_path %>

app/views/nodes/index.html.erb
<h1>Listing nodes</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Content</th>
    <th>User</th>
    <th>Views</th>
    <th>Voteup</th>
    <th>Votedown</th>
    <th>Root</th>
    <th>Category</th>
    <th>Type</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @nodes.each do |node| %>
  <tr>
    <td><%= node.title %></td>
    <td><%= node.content %></td>
    <td><%= node.user_id %></td>
    <td><%= node.views %></td>
    <td><%= node.voteUp %></td>
    <td><%= node.voteDown %></td>
    <td><%= node.root %></td>
    <td><%= node.category_id %></td>
    <td><%= node.type_id %></td>
    <td><%= link_to 'Show', node %></td>
    <td><%= link_to 'Edit', edit_node_path(node) %></td>
    <td><%= link_to 'Destroy', node, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Node', new_node_path %>

app/views/nodes/new.html.erb
<h1>New node</h1>

<%= render 'form' %>

<%= link_to 'Back', nodes_path %>

app/views/nodes/show.html.erb
<p id="notice"><%= notice %></p>
<div Class="content_left">
	<div class="story_root round">
	  <b> <%= @node.title %> </b><br />
	  <%= @node.content %> <br />
	  <div class="story_info round">
		  <b>User:</b> <%= User.find(@node.user_id).username %>
		  <b>Views:</b> <%= @node.views %>
		  <b>Like:</b> <%= @node.voteUp %> 
		  <b>DisLike:</b><%= @node.voteDown %>
	  </div>
	  
	  <%= link_to 'Edit', edit_node_path(@node), :class =>'edit_delete funkcije' %>
	  <%= link_to 'Destroy', @node, confirm: 'Are you sure?', method: :delete , :class =>'edit_delete funkcije' %>
	</div> 
	
	
	<% @node.story.each do |node| %>
	<div class="story_replay round">
	  	<b> <%= node.title %> </b><br />
		<%= node.content %> <br />
		<div class="story_info round">
		  <b>U:</b> <%= User.find(node.user_id).username %>
		  <b>V:</b> <%= node.views %>
		  <b>Like:</b> <%= node.voteUp %> 
		  <b>DisLike:</b><%= node.voteDown %>
		</div>
		<%= link_to 'Edit', edit_node_path(node), :class =>'edit_delete funkcije' %>
        <%= link_to 'Destroy', node, confirm: 'Are you sure?', method: :delete , :class =>'edit_delete funkcije' %>   
	</div> 
	   
	<% end %>
</div>

app/views/nodes/stories.html.erb
<h1>Stories</h1>
	
	<% @node.each do |node| %>
	<div class="story_replay round">
	  	<%= link_to node.title, node_path(node) %><br />
		<%= node.content %> <br />
		<div class="story_info round">
		  <b>U:</b> <%= User.find(node.user_id).username %>
		  <b>V:</b> <%= node.views %>
		  <b>Like:</b> <%= node.voteUp %> 
		  <b>DisLike:</b><%= node.voteDown %>
		</div>
		<%= link_to 'Edit', edit_node_path(node), :class =>'edit_delete funkcije' %>
        <%= link_to 'Destroy', node, confirm: 'Are you sure?', method: :delete , :class =>'edit_delete funkcije' %>   
	</div> 
	   
	<% end %>