config/routes.rb
FairyWhaleDemo::Application.routes.draw do
  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  resources :comments
  resources :categories
  resources :types
  resources :node_comments
  resources :nodes

  root :to => 'pages#home' #root
  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/home', :to => 'pages#home' #get "pages/home"
  match '/stories',   :to => 'nodes#stories' #get "pages/zgodbe"
  match '/about',   :to => 'pages#about' #get "pages/zgodba"
  match '/newstory', :to => 'nodes#new'
  match '/nodes/:id/add', :to => 'nodes#addnode'
  resources :nodes do
    member do
      get :zgodba
    end
  end

end

app/views/layouts/_footer.html.erb
<footer>
  <nav class="round">
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", '#' %></li>
      <li><%= link_to "Big Fat Whale Team", '#'%></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
        <%= image_tag("logo1.png", :alt => "Fairy Whale Logo", :class => "round") %>
        <nav class="round">
          <ul>
          	<li><%= link_to "Home", root_path %></li>
          	<li><%= link_to "Stories", stories_path %></li>
            <% if signed_in? %>
      		<li><%= link_to "Profile", current_user %></li>
      		<li><%= link_to "Sign out", signout_path, :method => :delete %></li>
      		<li id="funkcije"><%= link_to "(+) New story", newstory_path %></li>
      		<% else %>
      		<li><%= link_to "Sing in", signin_path %></li>
            <li><%= link_to "Create Account", signup_path %></li>
          	<% end %>
          </ul>
        </nav>
      </header>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>
<%= javascript_include_tag "application" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FairyWhale Demo App | <%= @title%></title>
  <%= csrf_meta_tag %>
  <%= render 'layouts/stylesheets' %>
</head>
<body>
<div class="container">
      <%= render 'layouts/header' %>
      <section class="round">
      	<% flash.each do |key, value| %>
          <div class="flash <%= key %>"><%= value %></div>
        <% end %>
        <%= yield %>
      </section>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
</body>
</html>